# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger: none

pool: kali-agent

steps:
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'My-Sonar-Server'
    scannerMode: 'Other'
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'My-Sonar-Server'
    scannerMode: 'Other'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install sonar:sonar'
    publishJUnitResults: false
    javaHomeOption: 'Path'
    jdkDirectory: '/opt/openlogic-openjdk-17.0.11+9-linux-x64'
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx3072m'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

